/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_AccessCorrelationID_H_
#define	_AccessCorrelationID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <UniversalString.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AccessCorrelationID_PR {
	AccessCorrelationID_PR_NOTHING,	/* No components present */
	AccessCorrelationID_PR_gPRS_Charging_Id,
	AccessCorrelationID_PR_accessNetworkChargingIdentifier
} AccessCorrelationID_PR;

/* AccessCorrelationID */
typedef struct AccessCorrelationID {
	AccessCorrelationID_PR present;
	union AccessCorrelationID_u {
		long	 gPRS_Charging_Id;
		UniversalString_t	 accessNetworkChargingIdentifier;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AccessCorrelationID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AccessCorrelationID;

#ifdef __cplusplus
}
#endif

#endif	/* _AccessCorrelationID_H_ */
