/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_IMSCommunicationServiceIdentifier_H_
#define	_IMSCommunicationServiceIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IMSCommunicationServiceIdentifier */
typedef OCTET_STRING_t	 IMSCommunicationServiceIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IMSCommunicationServiceIdentifier;
asn_struct_free_f IMSCommunicationServiceIdentifier_free;
asn_struct_print_f IMSCommunicationServiceIdentifier_print;
asn_constr_check_f IMSCommunicationServiceIdentifier_constraint;
ber_type_decoder_f IMSCommunicationServiceIdentifier_decode_ber;
der_type_encoder_f IMSCommunicationServiceIdentifier_encode_der;
xer_type_decoder_f IMSCommunicationServiceIdentifier_decode_xer;
xer_type_encoder_f IMSCommunicationServiceIdentifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _IMSCommunicationServiceIdentifier_H_ */
