/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_IMSRecord_H_
#define	_IMSRecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IMSRecord_PR {
	IMSRecord_PR_NOTHING,	/* No components present */
	IMSRecord_PR_sCSCFRecord,
	IMSRecord_PR_pCSCFRecord,
	IMSRecord_PR_iCSCFRecord,
	IMSRecord_PR_mRFCRecord,
	IMSRecord_PR_mGCFRecord,
	IMSRecord_PR_bGCFRecord,
	IMSRecord_PR_aSRecord
} IMSRecord_PR;

/* Forward declarations */
struct SCSCFRecord;
struct PCSCFRecord;
struct ICSCFRecord;
struct MRFCRecord;
struct MGCFRecord;
struct BGCFRecord;
struct ASRecord;

/* IMSRecord */
typedef struct IMSRecord {
	IMSRecord_PR present;
	union IMSRecord_u {
		struct SCSCFRecord	*sCSCFRecord;
		struct PCSCFRecord	*pCSCFRecord;
		struct ICSCFRecord	*iCSCFRecord;
		struct MRFCRecord	*mRFCRecord;
		struct MGCFRecord	*mGCFRecord;
		struct BGCFRecord	*bGCFRecord;
		struct ASRecord	*aSRecord;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IMSRecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IMSRecord;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SCSCFRecord.h"
#include "PCSCFRecord.h"
#include "ICSCFRecord.h"
#include "MRFCRecord.h"
#include "MGCFRecord.h"
#include "BGCFRecord.h"
#include "ASRecord.h"

#endif	/* _IMSRecord_H_ */
