/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#include <asn_internal.h>

#include "Incomplete-CDR-Indication.h"

static asn_TYPE_member_t asn_MBR_Incomplete_CDR_Indication_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Incomplete_CDR_Indication, aCRStartLost),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aCRStartLost"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Incomplete_CDR_Indication, aCRInterimLost),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ACRInterimLost,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aCRInterimLost"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Incomplete_CDR_Indication, aCRStopLost),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aCRStopLost"
		},
};
static ber_tlv_tag_t asn_DEF_Incomplete_CDR_Indication_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Incomplete_CDR_Indication_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* aCRStartLost at 378 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* aCRInterimLost at 379 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* aCRStopLost at 380 */
};
static uint8_t asn_MAP_Incomplete_CDR_Indication_mmap_1[(3 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7) | (1 << 6) | (1 << 5)
};
static asn_SET_specifics_t asn_SPC_Incomplete_CDR_Indication_specs_1 = {
	sizeof(struct Incomplete_CDR_Indication),
	offsetof(struct Incomplete_CDR_Indication, _asn_ctx),
	offsetof(struct Incomplete_CDR_Indication, _presence_map),
	asn_MAP_Incomplete_CDR_Indication_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_Incomplete_CDR_Indication_tag2el_1,	/* Same as above */
	3,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_Incomplete_CDR_Indication_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_Incomplete_CDR_Indication = {
	"Incomplete-CDR-Indication",
	"Incomplete-CDR-Indication",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Incomplete_CDR_Indication_tags_1,
	sizeof(asn_DEF_Incomplete_CDR_Indication_tags_1)
		/sizeof(asn_DEF_Incomplete_CDR_Indication_tags_1[0]), /* 1 */
	asn_DEF_Incomplete_CDR_Indication_tags_1,	/* Same as above */
	sizeof(asn_DEF_Incomplete_CDR_Indication_tags_1)
		/sizeof(asn_DEF_Incomplete_CDR_Indication_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Incomplete_CDR_Indication_1,
	3,	/* Elements count */
	&asn_SPC_Incomplete_CDR_Indication_specs_1	/* Additional specs */
};

