/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_InterOperatorIdentifiers_H_
#define	_InterOperatorIdentifiers_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UniversalString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InterOperatorIdentifiers */
typedef struct InterOperatorIdentifiers {
	UniversalString_t	*originatingIOI	/* OPTIONAL */;
	UniversalString_t	*terminatingIOI	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterOperatorIdentifiers_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterOperatorIdentifiers;

#ifdef __cplusplus
}
#endif

#endif	/* _InterOperatorIdentifiers_H_ */
