/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_NumberPortabilityRouting_H_
#define	_NumberPortabilityRouting_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UniversalString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NumberPortabilityRouting */
typedef UniversalString_t	 NumberPortabilityRouting_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NumberPortabilityRouting;
asn_struct_free_f NumberPortabilityRouting_free;
asn_struct_print_f NumberPortabilityRouting_print;
asn_constr_check_f NumberPortabilityRouting_constraint;
ber_type_decoder_f NumberPortabilityRouting_decode_ber;
der_type_encoder_f NumberPortabilityRouting_encode_der;
xer_type_decoder_f NumberPortabilityRouting_decode_xer;
xer_type_encoder_f NumberPortabilityRouting_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NumberPortabilityRouting_H_ */
