/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#include <asn_internal.h>

#include "S-CSCF-Information.h"

static asn_TYPE_member_t asn_MBR_mandatoryCapabilities_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (28 << 2)),
		0,
		&asn_DEF_UniversalString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_mandatoryCapabilities_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_mandatoryCapabilities_specs_2 = {
	sizeof(struct S_CSCF_Information__mandatoryCapabilities),
	offsetof(struct S_CSCF_Information__mandatoryCapabilities, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mandatoryCapabilities_2 = {
	"mandatoryCapabilities",
	"mandatoryCapabilities",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_mandatoryCapabilities_tags_2,
	sizeof(asn_DEF_mandatoryCapabilities_tags_2)
		/sizeof(asn_DEF_mandatoryCapabilities_tags_2[0]) - 1, /* 1 */
	asn_DEF_mandatoryCapabilities_tags_2,	/* Same as above */
	sizeof(asn_DEF_mandatoryCapabilities_tags_2)
		/sizeof(asn_DEF_mandatoryCapabilities_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_mandatoryCapabilities_2,
	1,	/* Single element */
	&asn_SPC_mandatoryCapabilities_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_optionalCapabilities_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (28 << 2)),
		0,
		&asn_DEF_UniversalString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_optionalCapabilities_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_optionalCapabilities_specs_4 = {
	sizeof(struct S_CSCF_Information__optionalCapabilities),
	offsetof(struct S_CSCF_Information__optionalCapabilities, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_optionalCapabilities_4 = {
	"optionalCapabilities",
	"optionalCapabilities",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_optionalCapabilities_tags_4,
	sizeof(asn_DEF_optionalCapabilities_tags_4)
		/sizeof(asn_DEF_optionalCapabilities_tags_4[0]) - 1, /* 1 */
	asn_DEF_optionalCapabilities_tags_4,	/* Same as above */
	sizeof(asn_DEF_optionalCapabilities_tags_4)
		/sizeof(asn_DEF_optionalCapabilities_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_optionalCapabilities_4,
	1,	/* Single element */
	&asn_SPC_optionalCapabilities_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_S_CSCF_Information_1[] = {
	{ ATF_POINTER, 3, offsetof(struct S_CSCF_Information, mandatoryCapabilities),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_mandatoryCapabilities_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mandatoryCapabilities"
		},
	{ ATF_POINTER, 2, offsetof(struct S_CSCF_Information, optionalCapabilities),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_optionalCapabilities_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"optionalCapabilities"
		},
	{ ATF_POINTER, 1, offsetof(struct S_CSCF_Information, serverName),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UniversalString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serverName"
		},
};
static ber_tlv_tag_t asn_DEF_S_CSCF_Information_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_S_CSCF_Information_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mandatoryCapabilities at 319 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* optionalCapabilities at 320 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* serverName at 321 */
};
static asn_SEQUENCE_specifics_t asn_SPC_S_CSCF_Information_specs_1 = {
	sizeof(struct S_CSCF_Information),
	offsetof(struct S_CSCF_Information, _asn_ctx),
	asn_MAP_S_CSCF_Information_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_S_CSCF_Information = {
	"S-CSCF-Information",
	"S-CSCF-Information",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_S_CSCF_Information_tags_1,
	sizeof(asn_DEF_S_CSCF_Information_tags_1)
		/sizeof(asn_DEF_S_CSCF_Information_tags_1[0]), /* 1 */
	asn_DEF_S_CSCF_Information_tags_1,	/* Same as above */
	sizeof(asn_DEF_S_CSCF_Information_tags_1)
		/sizeof(asn_DEF_S_CSCF_Information_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_S_CSCF_Information_1,
	3,	/* Elements count */
	&asn_SPC_S_CSCF_Information_specs_1	/* Additional specs */
};

