/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#include <asn_internal.h>

#include "SCSCFRecord.h"

static asn_TYPE_member_t asn_MBR_list_Of_SDP_Media_Components_22[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Media_Components_List,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_list_Of_SDP_Media_Components_tags_22[] = {
	(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_list_Of_SDP_Media_Components_specs_22 = {
	sizeof(struct SCSCFRecord__list_Of_SDP_Media_Components),
	offsetof(struct SCSCFRecord__list_Of_SDP_Media_Components, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_list_Of_SDP_Media_Components_22 = {
	"list-Of-SDP-Media-Components",
	"list-Of-SDP-Media-Components",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_list_Of_SDP_Media_Components_tags_22,
	sizeof(asn_DEF_list_Of_SDP_Media_Components_tags_22)
		/sizeof(asn_DEF_list_Of_SDP_Media_Components_tags_22[0]) - 1, /* 1 */
	asn_DEF_list_Of_SDP_Media_Components_tags_22,	/* Same as above */
	sizeof(asn_DEF_list_Of_SDP_Media_Components_tags_22)
		/sizeof(asn_DEF_list_Of_SDP_Media_Components_tags_22[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_list_Of_SDP_Media_Components_22,
	1,	/* Single element */
	&asn_SPC_list_Of_SDP_Media_Components_specs_22	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_list_Of_Message_Bodies_26[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_MessageBody,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_list_Of_Message_Bodies_tags_26[] = {
	(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_list_Of_Message_Bodies_specs_26 = {
	sizeof(struct SCSCFRecord__list_Of_Message_Bodies),
	offsetof(struct SCSCFRecord__list_Of_Message_Bodies, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_list_Of_Message_Bodies_26 = {
	"list-Of-Message-Bodies",
	"list-Of-Message-Bodies",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_list_Of_Message_Bodies_tags_26,
	sizeof(asn_DEF_list_Of_Message_Bodies_tags_26)
		/sizeof(asn_DEF_list_Of_Message_Bodies_tags_26[0]) - 1, /* 1 */
	asn_DEF_list_Of_Message_Bodies_tags_26,	/* Same as above */
	sizeof(asn_DEF_list_Of_Message_Bodies_tags_26)
		/sizeof(asn_DEF_list_Of_Message_Bodies_tags_26[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_list_Of_Message_Bodies_26,
	1,	/* Single element */
	&asn_SPC_list_Of_Message_Bodies_specs_26	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_list_of_subscription_ID_33[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (17 << 2)),
		0,
		&asn_DEF_SubscriptionID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_list_of_subscription_ID_tags_33[] = {
	(ASN_TAG_CLASS_CONTEXT | (31 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_list_of_subscription_ID_specs_33 = {
	sizeof(struct SCSCFRecord__list_of_subscription_ID),
	offsetof(struct SCSCFRecord__list_of_subscription_ID, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_list_of_subscription_ID_33 = {
	"list-of-subscription-ID",
	"list-of-subscription-ID",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_list_of_subscription_ID_tags_33,
	sizeof(asn_DEF_list_of_subscription_ID_tags_33)
		/sizeof(asn_DEF_list_of_subscription_ID_tags_33[0]) - 1, /* 1 */
	asn_DEF_list_of_subscription_ID_tags_33,	/* Same as above */
	sizeof(asn_DEF_list_of_subscription_ID_tags_33)
		/sizeof(asn_DEF_list_of_subscription_ID_tags_33[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_list_of_subscription_ID_33,
	1,	/* Single element */
	&asn_SPC_list_of_subscription_ID_specs_33	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_list_Of_Early_SDP_Media_Components_35[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Early_Media_Components_List,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_list_Of_Early_SDP_Media_Components_tags_35[] = {
	(ASN_TAG_CLASS_CONTEXT | (32 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_list_Of_Early_SDP_Media_Components_specs_35 = {
	sizeof(struct SCSCFRecord__list_Of_Early_SDP_Media_Components),
	offsetof(struct SCSCFRecord__list_Of_Early_SDP_Media_Components, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_list_Of_Early_SDP_Media_Components_35 = {
	"list-Of-Early-SDP-Media-Components",
	"list-Of-Early-SDP-Media-Components",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_list_Of_Early_SDP_Media_Components_tags_35,
	sizeof(asn_DEF_list_Of_Early_SDP_Media_Components_tags_35)
		/sizeof(asn_DEF_list_Of_Early_SDP_Media_Components_tags_35[0]) - 1, /* 1 */
	asn_DEF_list_Of_Early_SDP_Media_Components_tags_35,	/* Same as above */
	sizeof(asn_DEF_list_Of_Early_SDP_Media_Components_tags_35)
		/sizeof(asn_DEF_list_Of_Early_SDP_Media_Components_tags_35[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_list_Of_Early_SDP_Media_Components_35,
	1,	/* Single element */
	&asn_SPC_list_Of_Early_SDP_Media_Components_specs_35	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_applicationServersInformation_40[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ApplicationServersInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_applicationServersInformation_tags_40[] = {
	(ASN_TAG_CLASS_CONTEXT | (40 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_applicationServersInformation_specs_40 = {
	sizeof(struct SCSCFRecord__applicationServersInformation),
	offsetof(struct SCSCFRecord__applicationServersInformation, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_applicationServersInformation_40 = {
	"applicationServersInformation",
	"applicationServersInformation",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_applicationServersInformation_tags_40,
	sizeof(asn_DEF_applicationServersInformation_tags_40)
		/sizeof(asn_DEF_applicationServersInformation_tags_40[0]) - 1, /* 1 */
	asn_DEF_applicationServersInformation_tags_40,	/* Same as above */
	sizeof(asn_DEF_applicationServersInformation_tags_40)
		/sizeof(asn_DEF_applicationServersInformation_tags_40[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_applicationServersInformation_40,
	1,	/* Single element */
	&asn_SPC_applicationServersInformation_specs_40	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SCSCFRecord_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SCSCFRecord, recordType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RecordType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recordType"
		},
	{ ATF_POINTER, 36, offsetof(struct SCSCFRecord, retransmission),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"retransmission"
		},
	{ ATF_POINTER, 35, offsetof(struct SCSCFRecord, sIP_Method),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SIP_Method,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sIP-Method"
		},
	{ ATF_POINTER, 34, offsetof(struct SCSCFRecord, role_of_Node),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Role_of_Node,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"role-of-Node"
		},
	{ ATF_POINTER, 33, offsetof(struct SCSCFRecord, nodeAddress),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NodeAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"nodeAddress"
		},
	{ ATF_POINTER, 32, offsetof(struct SCSCFRecord, session_Id),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Session_Id,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"session-Id"
		},
	{ ATF_POINTER, 31, offsetof(struct SCSCFRecord, list_Of_Calling_Party_Address),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ListOfInvolvedParties,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"list-Of-Calling-Party-Address"
		},
	{ ATF_POINTER, 30, offsetof(struct SCSCFRecord, called_Party_Address),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_InvolvedParty,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"called-Party-Address"
		},
	{ ATF_POINTER, 29, offsetof(struct SCSCFRecord, privateUserID),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UniversalString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"privateUserID"
		},
	{ ATF_POINTER, 28, offsetof(struct SCSCFRecord, serviceRequestTimeStamp),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serviceRequestTimeStamp"
		},
	{ ATF_POINTER, 27, offsetof(struct SCSCFRecord, serviceDeliveryStartTimeStamp),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serviceDeliveryStartTimeStamp"
		},
	{ ATF_POINTER, 26, offsetof(struct SCSCFRecord, serviceDeliveryEndTimeStamp),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serviceDeliveryEndTimeStamp"
		},
	{ ATF_POINTER, 25, offsetof(struct SCSCFRecord, recordOpeningTime),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recordOpeningTime"
		},
	{ ATF_POINTER, 24, offsetof(struct SCSCFRecord, recordClosureTime),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recordClosureTime"
		},
	{ ATF_POINTER, 23, offsetof(struct SCSCFRecord, interOperatorIdentifiers),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InterOperatorIdentifierlist,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"interOperatorIdentifiers"
		},
	{ ATF_POINTER, 22, offsetof(struct SCSCFRecord, localRecordSequenceNumber),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LocalSequenceNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"localRecordSequenceNumber"
		},
	{ ATF_POINTER, 21, offsetof(struct SCSCFRecord, recordSequenceNumber),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recordSequenceNumber"
		},
	{ ATF_POINTER, 20, offsetof(struct SCSCFRecord, causeForRecordClosing),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CauseForRecordClosing,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"causeForRecordClosing"
		},
	{ ATF_POINTER, 19, offsetof(struct SCSCFRecord, incomplete_CDR_Indication),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Incomplete_CDR_Indication,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"incomplete-CDR-Indication"
		},
	{ ATF_POINTER, 18, offsetof(struct SCSCFRecord, iMS_Charging_Identifier),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IMS_Charging_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iMS-Charging-Identifier"
		},
	{ ATF_POINTER, 17, offsetof(struct SCSCFRecord, list_Of_SDP_Media_Components),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_list_Of_SDP_Media_Components_22,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"list-Of-SDP-Media-Components"
		},
	{ ATF_POINTER, 16, offsetof(struct SCSCFRecord, gGSNaddress),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NodeAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"gGSNaddress"
		},
	{ ATF_POINTER, 15, offsetof(struct SCSCFRecord, serviceReasonReturnCode),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serviceReasonReturnCode"
		},
	{ ATF_POINTER, 14, offsetof(struct SCSCFRecord, list_Of_Message_Bodies),
		(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_list_Of_Message_Bodies_26,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"list-Of-Message-Bodies"
		},
	{ ATF_POINTER, 13, offsetof(struct SCSCFRecord, expiresInformation),
		(ASN_TAG_CLASS_CONTEXT | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"expiresInformation"
		},
	{ ATF_POINTER, 12, offsetof(struct SCSCFRecord, list_Of_Associated_URI),
		(ASN_TAG_CLASS_CONTEXT | (27 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ListOfInvolvedParties,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"list-Of-Associated-URI"
		},
	{ ATF_POINTER, 11, offsetof(struct SCSCFRecord, event),
		(ASN_TAG_CLASS_CONTEXT | (28 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"event"
		},
	{ ATF_POINTER, 10, offsetof(struct SCSCFRecord, accessNetworkInformation),
		(ASN_TAG_CLASS_CONTEXT | (29 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accessNetworkInformation"
		},
	{ ATF_POINTER, 9, offsetof(struct SCSCFRecord, serviceContextID),
		(ASN_TAG_CLASS_CONTEXT | (30 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ServiceContextID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serviceContextID"
		},
	{ ATF_POINTER, 8, offsetof(struct SCSCFRecord, list_of_subscription_ID),
		(ASN_TAG_CLASS_CONTEXT | (31 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_list_of_subscription_ID_33,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"list-of-subscription-ID"
		},
	{ ATF_POINTER, 7, offsetof(struct SCSCFRecord, list_Of_Early_SDP_Media_Components),
		(ASN_TAG_CLASS_CONTEXT | (32 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_list_Of_Early_SDP_Media_Components_35,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"list-Of-Early-SDP-Media-Components"
		},
	{ ATF_POINTER, 6, offsetof(struct SCSCFRecord, iMSCommunicationServiceIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (33 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IMSCommunicationServiceIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iMSCommunicationServiceIdentifier"
		},
	{ ATF_POINTER, 5, offsetof(struct SCSCFRecord, numberPortabilityRouting),
		(ASN_TAG_CLASS_CONTEXT | (34 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NumberPortabilityRouting,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numberPortabilityRouting"
		},
	{ ATF_POINTER, 4, offsetof(struct SCSCFRecord, carrierSelectRouting),
		(ASN_TAG_CLASS_CONTEXT | (35 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CarrierSelectRouting,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"carrierSelectRouting"
		},
	{ ATF_POINTER, 3, offsetof(struct SCSCFRecord, applicationServersInformation),
		(ASN_TAG_CLASS_CONTEXT | (40 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_applicationServersInformation_40,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"applicationServersInformation"
		},
	{ ATF_POINTER, 2, offsetof(struct SCSCFRecord, requested_Party_Address),
		(ASN_TAG_CLASS_CONTEXT | (41 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_InvolvedParty,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requested-Party-Address"
		},
	{ ATF_POINTER, 1, offsetof(struct SCSCFRecord, list_Of_Called_Asserted_Identity),
		(ASN_TAG_CLASS_CONTEXT | (42 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ListOfInvolvedParties,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"list-Of-Called-Asserted-Identity"
		},
};
static ber_tlv_tag_t asn_DEF_SCSCFRecord_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SCSCFRecord_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* recordType at 42 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* retransmission at 43 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sIP-Method at 44 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* role-of-Node at 45 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* nodeAddress at 46 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* session-Id at 47 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* list-Of-Calling-Party-Address at 48 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* called-Party-Address at 49 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* privateUserID at 50 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* serviceRequestTimeStamp at 51 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* serviceDeliveryStartTimeStamp at 52 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* serviceDeliveryEndTimeStamp at 53 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* recordOpeningTime at 54 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* recordClosureTime at 55 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* interOperatorIdentifiers at 56 */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 }, /* localRecordSequenceNumber at 57 */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 16, 0, 0 }, /* recordSequenceNumber at 58 */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 17, 0, 0 }, /* causeForRecordClosing at 59 */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 18, 0, 0 }, /* incomplete-CDR-Indication at 60 */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 19, 0, 0 }, /* iMS-Charging-Identifier at 61 */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 20, 0, 0 }, /* list-Of-SDP-Media-Components at 62 */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 21, 0, 0 }, /* gGSNaddress at 63 */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 22, 0, 0 }, /* serviceReasonReturnCode at 64 */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 23, 0, 0 }, /* list-Of-Message-Bodies at 65 */
    { (ASN_TAG_CLASS_CONTEXT | (26 << 2)), 24, 0, 0 }, /* expiresInformation at 67 */
    { (ASN_TAG_CLASS_CONTEXT | (27 << 2)), 25, 0, 0 }, /* list-Of-Associated-URI at 68 */
    { (ASN_TAG_CLASS_CONTEXT | (28 << 2)), 26, 0, 0 }, /* event at 69 */
    { (ASN_TAG_CLASS_CONTEXT | (29 << 2)), 27, 0, 0 }, /* accessNetworkInformation at 70 */
    { (ASN_TAG_CLASS_CONTEXT | (30 << 2)), 28, 0, 0 }, /* serviceContextID at 71 */
    { (ASN_TAG_CLASS_CONTEXT | (31 << 2)), 29, 0, 0 }, /* list-of-subscription-ID at 72 */
    { (ASN_TAG_CLASS_CONTEXT | (32 << 2)), 30, 0, 0 }, /* list-Of-Early-SDP-Media-Components at 73 */
    { (ASN_TAG_CLASS_CONTEXT | (33 << 2)), 31, 0, 0 }, /* iMSCommunicationServiceIdentifier at 74 */
    { (ASN_TAG_CLASS_CONTEXT | (34 << 2)), 32, 0, 0 }, /* numberPortabilityRouting at 75 */
    { (ASN_TAG_CLASS_CONTEXT | (35 << 2)), 33, 0, 0 }, /* carrierSelectRouting at 76 */
    { (ASN_TAG_CLASS_CONTEXT | (40 << 2)), 34, 0, 0 }, /* applicationServersInformation at 77 */
    { (ASN_TAG_CLASS_CONTEXT | (41 << 2)), 35, 0, 0 }, /* requested-Party-Address at 78 */
    { (ASN_TAG_CLASS_CONTEXT | (42 << 2)), 36, 0, 0 } /* list-Of-Called-Asserted-Identity at 79 */
};
static uint8_t asn_MAP_SCSCFRecord_mmap_1[(37 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7) | (0 << 6) | (0 << 5) | (0 << 4) | (0 << 3) | (0 << 2) | (0 << 1) | (0 << 0),
	(0 << 7) | (0 << 6) | (0 << 5) | (0 << 4) | (0 << 3) | (0 << 2) | (0 << 1) | (0 << 0),
	(0 << 7) | (0 << 6) | (0 << 5) | (0 << 4) | (0 << 3) | (0 << 2) | (0 << 1) | (0 << 0),
	(0 << 7) | (0 << 6) | (0 << 5) | (0 << 4) | (0 << 3) | (0 << 2) | (0 << 1) | (0 << 0),
	(0 << 7) | (0 << 6) | (0 << 5) | (0 << 4) | (0 << 3)
};
static asn_SET_specifics_t asn_SPC_SCSCFRecord_specs_1 = {
	sizeof(struct SCSCFRecord),
	offsetof(struct SCSCFRecord, _asn_ctx),
	offsetof(struct SCSCFRecord, _presence_map),
	asn_MAP_SCSCFRecord_tag2el_1,
	37,	/* Count of tags in the map */
	asn_MAP_SCSCFRecord_tag2el_1,	/* Same as above */
	37,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_SCSCFRecord_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_SCSCFRecord = {
	"SCSCFRecord",
	"SCSCFRecord",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SCSCFRecord_tags_1,
	sizeof(asn_DEF_SCSCFRecord_tags_1)
		/sizeof(asn_DEF_SCSCFRecord_tags_1[0]), /* 1 */
	asn_DEF_SCSCFRecord_tags_1,	/* Same as above */
	sizeof(asn_DEF_SCSCFRecord_tags_1)
		/sizeof(asn_DEF_SCSCFRecord_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SCSCFRecord_1,
	37,	/* Elements count */
	&asn_SPC_SCSCFRecord_specs_1	/* Additional specs */
};

