/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_SDP_Media_Description_H_
#define	_SDP_Media_Description_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UniversalString.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SDP-Media-Description */
typedef struct SDP_Media_Description {
	A_SEQUENCE_OF(UniversalString_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SDP_Media_Description_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SDP_Media_Description;

#ifdef __cplusplus
}
#endif

#endif	/* _SDP_Media_Description_H_ */
