/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_ServedPartyIPAddress_H_
#define	_ServedPartyIPAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IPAddress.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ServedPartyIPAddress */
typedef IPAddress_t	 ServedPartyIPAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServedPartyIPAddress;
asn_struct_free_f ServedPartyIPAddress_free;
asn_struct_print_f ServedPartyIPAddress_print;
asn_constr_check_f ServedPartyIPAddress_constraint;
ber_type_decoder_f ServedPartyIPAddress_decode_ber;
der_type_encoder_f ServedPartyIPAddress_encode_der;
xer_type_decoder_f ServedPartyIPAddress_decode_xer;
xer_type_encoder_f ServedPartyIPAddress_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ServedPartyIPAddress_H_ */
