/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_TrunkGroupID_H_
#define	_TrunkGroupID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UniversalString.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TrunkGroupID_PR {
	TrunkGroupID_PR_NOTHING,	/* No components present */
	TrunkGroupID_PR_incoming,
	TrunkGroupID_PR_outgoing
} TrunkGroupID_PR;

/* TrunkGroupID */
typedef struct TrunkGroupID {
	TrunkGroupID_PR present;
	union TrunkGroupID_u {
		UniversalString_t	 incoming;
		UniversalString_t	 outgoing;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TrunkGroupID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TrunkGroupID;

#ifdef __cplusplus
}
#endif

#endif	/* _TrunkGroupID_H_ */
