/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_ACRInterimLost_H_
#define	_ACRInterimLost_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ACRInterimLost {
	ACRInterimLost_no	= 0,
	ACRInterimLost_yes	= 1,
	ACRInterimLost_unknown	= 2
} e_ACRInterimLost;

/* ACRInterimLost */
typedef long	 ACRInterimLost_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ACRInterimLost;
asn_struct_free_f ACRInterimLost_free;
asn_struct_print_f ACRInterimLost_print;
asn_constr_check_f ACRInterimLost_constraint;
ber_type_decoder_f ACRInterimLost_decode_ber;
der_type_encoder_f ACRInterimLost_encode_der;
xer_type_decoder_f ACRInterimLost_decode_xer;
xer_type_encoder_f ACRInterimLost_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ACRInterimLost_H_ */
