/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_ApplicationServersInformation_H_
#define	_ApplicationServersInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NodeAddress;
struct InvolvedParty;

/* ApplicationServersInformation */
typedef struct ApplicationServersInformation {
	struct NodeAddress	*applicationServersInvolved	/* OPTIONAL */;
	struct ApplicationServersInformation__applicationProvidedCalledParties {
		A_SEQUENCE_OF(struct InvolvedParty) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *applicationProvidedCalledParties;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ApplicationServersInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ApplicationServersInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NodeAddress.h"
#include "InvolvedParty.h"

#endif	/* _ApplicationServersInformation_H_ */
