/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_CarrierSelectRouting_H_
#define	_CarrierSelectRouting_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UniversalString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CarrierSelectRouting */
typedef UniversalString_t	 CarrierSelectRouting_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CarrierSelectRouting;
asn_struct_free_f CarrierSelectRouting_free;
asn_struct_print_f CarrierSelectRouting_print;
asn_constr_check_f CarrierSelectRouting_constraint;
ber_type_decoder_f CarrierSelectRouting_decode_ber;
der_type_encoder_f CarrierSelectRouting_encode_der;
xer_type_decoder_f CarrierSelectRouting_decode_xer;
xer_type_encoder_f CarrierSelectRouting_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CarrierSelectRouting_H_ */
