/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#include <asn_internal.h>

#include "Early-Media-Components-List.h"

static asn_TYPE_member_t asn_MBR_sDP_Media_Components_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SDP_Media_Component,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_sDP_Media_Components_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_sDP_Media_Components_specs_4 = {
	sizeof(struct Early_Media_Components_List__sDP_Media_Components),
	offsetof(struct Early_Media_Components_List__sDP_Media_Components, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sDP_Media_Components_4 = {
	"sDP-Media-Components",
	"sDP-Media-Components",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_sDP_Media_Components_tags_4,
	sizeof(asn_DEF_sDP_Media_Components_tags_4)
		/sizeof(asn_DEF_sDP_Media_Components_tags_4[0]) - 1, /* 1 */
	asn_DEF_sDP_Media_Components_tags_4,	/* Same as above */
	sizeof(asn_DEF_sDP_Media_Components_tags_4)
		/sizeof(asn_DEF_sDP_Media_Components_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_sDP_Media_Components_4,
	1,	/* Single element */
	&asn_SPC_sDP_Media_Components_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_sDP_Session_Description_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (28 << 2)),
		0,
		&asn_DEF_UniversalString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_sDP_Session_Description_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_sDP_Session_Description_specs_7 = {
	sizeof(struct Early_Media_Components_List__sDP_Session_Description),
	offsetof(struct Early_Media_Components_List__sDP_Session_Description, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sDP_Session_Description_7 = {
	"sDP-Session-Description",
	"sDP-Session-Description",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_sDP_Session_Description_tags_7,
	sizeof(asn_DEF_sDP_Session_Description_tags_7)
		/sizeof(asn_DEF_sDP_Session_Description_tags_7[0]) - 1, /* 1 */
	asn_DEF_sDP_Session_Description_tags_7,	/* Same as above */
	sizeof(asn_DEF_sDP_Session_Description_tags_7)
		/sizeof(asn_DEF_sDP_Session_Description_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_sDP_Session_Description_7,
	1,	/* Single element */
	&asn_SPC_sDP_Session_Description_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Early_Media_Components_List_1[] = {
	{ ATF_POINTER, 5, offsetof(struct Early_Media_Components_List, sDP_Offer_Timestamp),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sDP-Offer-Timestamp"
		},
	{ ATF_POINTER, 4, offsetof(struct Early_Media_Components_List, sDP_Answer_Timestamp),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sDP-Answer-Timestamp"
		},
	{ ATF_POINTER, 3, offsetof(struct Early_Media_Components_List, sDP_Media_Components),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_sDP_Media_Components_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sDP-Media-Components"
		},
	{ ATF_POINTER, 2, offsetof(struct Early_Media_Components_List, mediaInitiatorFlag),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mediaInitiatorFlag"
		},
	{ ATF_POINTER, 1, offsetof(struct Early_Media_Components_List, sDP_Session_Description),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_sDP_Session_Description_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sDP-Session-Description"
		},
};
static ber_tlv_tag_t asn_DEF_Early_Media_Components_List_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Early_Media_Components_List_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sDP-Offer-Timestamp at 417 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sDP-Answer-Timestamp at 418 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sDP-Media-Components at 419 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* mediaInitiatorFlag at 420 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* sDP-Session-Description at 421 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Early_Media_Components_List_specs_1 = {
	sizeof(struct Early_Media_Components_List),
	offsetof(struct Early_Media_Components_List, _asn_ctx),
	asn_MAP_Early_Media_Components_List_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Early_Media_Components_List = {
	"Early-Media-Components-List",
	"Early-Media-Components-List",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Early_Media_Components_List_tags_1,
	sizeof(asn_DEF_Early_Media_Components_List_tags_1)
		/sizeof(asn_DEF_Early_Media_Components_List_tags_1[0]), /* 1 */
	asn_DEF_Early_Media_Components_List_tags_1,	/* Same as above */
	sizeof(asn_DEF_Early_Media_Components_List_tags_1)
		/sizeof(asn_DEF_Early_Media_Components_List_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Early_Media_Components_List_1,
	5,	/* Elements count */
	&asn_SPC_Early_Media_Components_List_specs_1	/* Additional specs */
};

