/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#include <asn_internal.h>

#include "IMSRecord.h"

static asn_TYPE_member_t asn_MBR_IMSRecord_1[] = {
	{ ATF_POINTER, 0, offsetof(struct IMSRecord, choice.sCSCFRecord),
		(ASN_TAG_CLASS_CONTEXT | (63 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SCSCFRecord,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sCSCFRecord"
		},
	{ ATF_POINTER, 0, offsetof(struct IMSRecord, choice.pCSCFRecord),
		(ASN_TAG_CLASS_CONTEXT | (64 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PCSCFRecord,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"pCSCFRecord"
		},
	{ ATF_POINTER, 0, offsetof(struct IMSRecord, choice.iCSCFRecord),
		(ASN_TAG_CLASS_CONTEXT | (65 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ICSCFRecord,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iCSCFRecord"
		},
	{ ATF_POINTER, 0, offsetof(struct IMSRecord, choice.mRFCRecord),
		(ASN_TAG_CLASS_CONTEXT | (66 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MRFCRecord,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mRFCRecord"
		},
	{ ATF_POINTER, 0, offsetof(struct IMSRecord, choice.mGCFRecord),
		(ASN_TAG_CLASS_CONTEXT | (67 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MGCFRecord,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mGCFRecord"
		},
	{ ATF_POINTER, 0, offsetof(struct IMSRecord, choice.bGCFRecord),
		(ASN_TAG_CLASS_CONTEXT | (68 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BGCFRecord,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bGCFRecord"
		},
	{ ATF_POINTER, 0, offsetof(struct IMSRecord, choice.aSRecord),
		(ASN_TAG_CLASS_CONTEXT | (69 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASRecord,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aSRecord"
		},
};
static asn_TYPE_tag2member_t asn_MAP_IMSRecord_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (63 << 2)), 0, 0, 0 }, /* sCSCFRecord at 27 */
    { (ASN_TAG_CLASS_CONTEXT | (64 << 2)), 1, 0, 0 }, /* pCSCFRecord at 28 */
    { (ASN_TAG_CLASS_CONTEXT | (65 << 2)), 2, 0, 0 }, /* iCSCFRecord at 29 */
    { (ASN_TAG_CLASS_CONTEXT | (66 << 2)), 3, 0, 0 }, /* mRFCRecord at 30 */
    { (ASN_TAG_CLASS_CONTEXT | (67 << 2)), 4, 0, 0 }, /* mGCFRecord at 31 */
    { (ASN_TAG_CLASS_CONTEXT | (68 << 2)), 5, 0, 0 }, /* bGCFRecord at 32 */
    { (ASN_TAG_CLASS_CONTEXT | (69 << 2)), 6, 0, 0 } /* aSRecord at 36 */
};
static asn_CHOICE_specifics_t asn_SPC_IMSRecord_specs_1 = {
	sizeof(struct IMSRecord),
	offsetof(struct IMSRecord, _asn_ctx),
	offsetof(struct IMSRecord, present),
	sizeof(((struct IMSRecord *)0)->present),
	asn_MAP_IMSRecord_tag2el_1,
	7,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_IMSRecord = {
	"IMSRecord",
	"IMSRecord",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_IMSRecord_1,
	7,	/* Elements count */
	&asn_SPC_IMSRecord_specs_1	/* Additional specs */
};

