/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_InterOperatorIdentifierlist_H_
#define	_InterOperatorIdentifierlist_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct InterOperatorIdentifiers;

/* InterOperatorIdentifierlist */
typedef struct InterOperatorIdentifierlist {
	A_SEQUENCE_OF(struct InterOperatorIdentifiers) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterOperatorIdentifierlist_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterOperatorIdentifierlist;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "InterOperatorIdentifiers.h"

#endif	/* _InterOperatorIdentifierlist_H_ */
