/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_InvolvedParty_H_
#define	_InvolvedParty_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UniversalString.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum InvolvedParty_PR {
	InvolvedParty_PR_NOTHING,	/* No components present */
	InvolvedParty_PR_sIP_URI,
	InvolvedParty_PR_tEL_URI
} InvolvedParty_PR;

/* InvolvedParty */
typedef struct InvolvedParty {
	InvolvedParty_PR present;
	union InvolvedParty_u {
		UniversalString_t	 sIP_URI;
		UniversalString_t	 tEL_URI;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InvolvedParty_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InvolvedParty;

#ifdef __cplusplus
}
#endif

#endif	/* _InvolvedParty_H_ */
