/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_ListOfInvolvedParties_H_
#define	_ListOfInvolvedParties_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct InvolvedParty;

/* ListOfInvolvedParties */
typedef struct ListOfInvolvedParties {
	A_SEQUENCE_OF(struct InvolvedParty) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ListOfInvolvedParties_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ListOfInvolvedParties;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "InvolvedParty.h"

#endif	/* _ListOfInvolvedParties_H_ */
