/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_MessageBody_H_
#define	_MessageBody_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UniversalString.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct InvolvedParty;

/* MessageBody */
typedef struct MessageBody {
	UniversalString_t	 content_Type;
	UniversalString_t	*content_Disposition	/* OPTIONAL */;
	long	 content_Length;
	struct InvolvedParty	*originator	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MessageBody_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MessageBody;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "InvolvedParty.h"

#endif	/* _MessageBody_H_ */
