/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#include <asn_internal.h>

#include "MessageBody.h"

static asn_TYPE_member_t asn_MBR_MessageBody_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MessageBody, content_Type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UniversalString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"content-Type"
		},
	{ ATF_POINTER, 1, offsetof(struct MessageBody, content_Disposition),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UniversalString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"content-Disposition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MessageBody, content_Length),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"content-Length"
		},
	{ ATF_POINTER, 1, offsetof(struct MessageBody, originator),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_InvolvedParty,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"originator"
		},
};
static ber_tlv_tag_t asn_DEF_MessageBody_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_MessageBody_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* content-Type at 428 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* content-Disposition at 429 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* content-Length at 430 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* originator at 431 */
};
static asn_SEQUENCE_specifics_t asn_SPC_MessageBody_specs_1 = {
	sizeof(struct MessageBody),
	offsetof(struct MessageBody, _asn_ctx),
	asn_MAP_MessageBody_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_MessageBody = {
	"MessageBody",
	"MessageBody",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MessageBody_tags_1,
	sizeof(asn_DEF_MessageBody_tags_1)
		/sizeof(asn_DEF_MessageBody_tags_1[0]), /* 1 */
	asn_DEF_MessageBody_tags_1,	/* Same as above */
	sizeof(asn_DEF_MessageBody_tags_1)
		/sizeof(asn_DEF_MessageBody_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_MessageBody_1,
	4,	/* Elements count */
	&asn_SPC_MessageBody_specs_1	/* Additional specs */
};

