/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_S_CSCF_Information_H_
#define	_S_CSCF_Information_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UniversalString.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* S-CSCF-Information */
typedef struct S_CSCF_Information {
	struct S_CSCF_Information__mandatoryCapabilities {
		A_SEQUENCE_OF(UniversalString_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *mandatoryCapabilities;
	struct S_CSCF_Information__optionalCapabilities {
		A_SEQUENCE_OF(UniversalString_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *optionalCapabilities;
	UniversalString_t	*serverName	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S_CSCF_Information_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S_CSCF_Information;

#ifdef __cplusplus
}
#endif

#endif	/* _S_CSCF_Information_H_ */
