/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#include <asn_internal.h>

#include "SDP-Media-Component.h"

static asn_TYPE_member_t asn_MBR_SDP_Media_Component_1[] = {
	{ ATF_POINTER, 4, offsetof(struct SDP_Media_Component, sDP_Media_Name),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UniversalString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sDP-Media-Name"
		},
	{ ATF_POINTER, 3, offsetof(struct SDP_Media_Component, sDP_Media_Descriptions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SDP_Media_Description,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sDP-Media-Descriptions"
		},
	{ ATF_POINTER, 2, offsetof(struct SDP_Media_Component, accessCorrelationID),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_AccessCorrelationID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accessCorrelationID"
		},
	{ ATF_POINTER, 1, offsetof(struct SDP_Media_Component, authorized_QoS),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UniversalString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"authorized-QoS"
		},
};
static ber_tlv_tag_t asn_DEF_SDP_Media_Component_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SDP_Media_Component_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sDP-Media-Name at 396 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sDP-Media-Descriptions at 397 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* gPRS-Charging-Id at 335 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* authorized-QoS at 399 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 2, 0, 0 } /* accessNetworkChargingIdentifier at 336 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SDP_Media_Component_specs_1 = {
	sizeof(struct SDP_Media_Component),
	offsetof(struct SDP_Media_Component, _asn_ctx),
	asn_MAP_SDP_Media_Component_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SDP_Media_Component = {
	"SDP-Media-Component",
	"SDP-Media-Component",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SDP_Media_Component_tags_1,
	sizeof(asn_DEF_SDP_Media_Component_tags_1)
		/sizeof(asn_DEF_SDP_Media_Component_tags_1[0]), /* 1 */
	asn_DEF_SDP_Media_Component_tags_1,	/* Same as above */
	sizeof(asn_DEF_SDP_Media_Component_tags_1)
		/sizeof(asn_DEF_SDP_Media_Component_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SDP_Media_Component_1,
	4,	/* Elements count */
	&asn_SPC_SDP_Media_Component_specs_1	/* Additional specs */
};

