/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "GenericChargingDataTypes"
 * 	found in "generic_charging_DataTypes.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_ServiceContextID_H_
#define	_ServiceContextID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ServiceContextID */
typedef UTF8String_t	 ServiceContextID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceContextID;
asn_struct_free_f ServiceContextID_free;
asn_struct_print_f ServiceContextID_print;
asn_constr_check_f ServiceContextID_constraint;
ber_type_decoder_f ServiceContextID_decode_ber;
der_type_encoder_f ServiceContextID_encode_der;
xer_type_decoder_f ServiceContextID_decode_xer;
xer_type_encoder_f ServiceContextID_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ServiceContextID_H_ */
