/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "GenericChargingDataTypes"
 * 	found in "generic_charging_DataTypes.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_ServiceSpecificInfo_H_
#define	_ServiceSpecificInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UniversalString.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ServiceSpecificInfo */
typedef struct ServiceSpecificInfo {
	UniversalString_t	*serviceSpecificData	/* OPTIONAL */;
	long	*serviceSpecificType	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServiceSpecificInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceSpecificInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _ServiceSpecificInfo_H_ */
