/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_Session_Id_H_
#define	_Session_Id_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UniversalString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Session-Id */
typedef UniversalString_t	 Session_Id_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Session_Id;
asn_struct_free_f Session_Id_free;
asn_struct_print_f Session_Id_print;
asn_constr_check_f Session_Id_constraint;
ber_type_decoder_f Session_Id_decode_ber;
der_type_encoder_f Session_Id_encode_der;
xer_type_decoder_f Session_Id_decode_xer;
xer_type_encoder_f Session_Id_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Session_Id_H_ */
