/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "GenericChargingDataTypes"
 * 	found in "generic_charging_DataTypes.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#include <asn_internal.h>

#include "SubscriptionID.h"

static asn_TYPE_member_t asn_MBR_SubscriptionID_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SubscriptionID, subscriptionIDType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SubscriptionIDType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"subscriptionIDType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubscriptionID, subscriptionIDData),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"subscriptionIDData"
		},
};
static ber_tlv_tag_t asn_DEF_SubscriptionID_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SubscriptionID_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* subscriptionIDType at 243 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* subscriptionIDData at 244 */
};
static uint8_t asn_MAP_SubscriptionID_mmap_1[(2 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7) | (1 << 6)
};
static asn_SET_specifics_t asn_SPC_SubscriptionID_specs_1 = {
	sizeof(struct SubscriptionID),
	offsetof(struct SubscriptionID, _asn_ctx),
	offsetof(struct SubscriptionID, _presence_map),
	asn_MAP_SubscriptionID_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_SubscriptionID_tag2el_1,	/* Same as above */
	2,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_SubscriptionID_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_SubscriptionID = {
	"SubscriptionID",
	"SubscriptionID",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SubscriptionID_tags_1,
	sizeof(asn_DEF_SubscriptionID_tags_1)
		/sizeof(asn_DEF_SubscriptionID_tags_1[0]), /* 1 */
	asn_DEF_SubscriptionID_tags_1,	/* Same as above */
	sizeof(asn_DEF_SubscriptionID_tags_1)
		/sizeof(asn_DEF_SubscriptionID_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SubscriptionID_1,
	2,	/* Elements count */
	&asn_SPC_SubscriptionID_specs_1	/* Additional specs */
};

