/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "GenericChargingDataTypes"
 * 	found in "generic_charging_DataTypes.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_SubscriptionID_H_
#define	_SubscriptionID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SubscriptionIDType.h"
#include <UTF8String.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum SubscriptionID_PR {
	SubscriptionID_PR_subscriptionIDType,	/* Member subscriptionIDType is present */
	SubscriptionID_PR_subscriptionIDData,	/* Member subscriptionIDData is present */
} SubscriptionID_PR;

/* SubscriptionID */
typedef struct SubscriptionID {
	SubscriptionIDType_t	 subscriptionIDType;
	UTF8String_t	 subscriptionIDData;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pSubscriptionID, SubscriptionID_PR_x) */
	unsigned int _presence_map
		[((2+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SubscriptionID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SubscriptionID;

#ifdef __cplusplus
}
#endif

#endif	/* _SubscriptionID_H_ */
