/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#ifndef	_TransmissionMedium_H_
#define	_TransmissionMedium_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TransmissionMedium */
typedef struct TransmissionMedium {
	OCTET_STRING_t	*tMR	/* OPTIONAL */;
	OCTET_STRING_t	*tMU	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TransmissionMedium_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TransmissionMedium;

#ifdef __cplusplus
}
#endif

#endif	/* _TransmissionMedium_H_ */
