/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "IMSChargingDataTypes"
 * 	found in "ims_charging-data_types.asn1"
 * 	`asn1c -fnative-types -fcompound-names -findirect-choice -fnative-types`
 */

#include <asn_internal.h>

#include "TransmissionMedium.h"

static int
memb_tMR_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_tMU_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_TransmissionMedium_1[] = {
	{ ATF_POINTER, 2, offsetof(struct TransmissionMedium, tMR),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_tMR_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"tMR"
		},
	{ ATF_POINTER, 1, offsetof(struct TransmissionMedium, tMU),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_tMU_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"tMU"
		},
};
static ber_tlv_tag_t asn_DEF_TransmissionMedium_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_TransmissionMedium_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* tMR at 436 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* tMU at 437 */
};
static asn_SEQUENCE_specifics_t asn_SPC_TransmissionMedium_specs_1 = {
	sizeof(struct TransmissionMedium),
	offsetof(struct TransmissionMedium, _asn_ctx),
	asn_MAP_TransmissionMedium_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TransmissionMedium = {
	"TransmissionMedium",
	"TransmissionMedium",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TransmissionMedium_tags_1,
	sizeof(asn_DEF_TransmissionMedium_tags_1)
		/sizeof(asn_DEF_TransmissionMedium_tags_1[0]), /* 1 */
	asn_DEF_TransmissionMedium_tags_1,	/* Same as above */
	sizeof(asn_DEF_TransmissionMedium_tags_1)
		/sizeof(asn_DEF_TransmissionMedium_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TransmissionMedium_1,
	2,	/* Elements count */
	&asn_SPC_TransmissionMedium_specs_1	/* Additional specs */
};

